excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
url: blog.gentrop.com
title: Gentrop Blog
email: luciano.faria@gentrop.com
author: Luciano Faria
description: Gentrop Blog
gems : [jekyll-paginate]
paginate: 4
google_analytics: 
