excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
url: http://gentrop.github.io/blog
title: Gentrop Blog
email: luciano.faria@gentrop.com
author: Luciano Faria
description: Gentrop Blog
gems : [jekyll-paginate]
baseurl: /blog
paginate: 4
google_analytics: 